#!/usr/bin/env python3
"""NotiFetch Brand LOI template - ReportLab (Report route, letter/contract type).
No cover (letter exclusion), no TOC -> SimpleDocTemplate + build().
Palette: design_engine palette-cascade --intent cold --mode minimal --harmony monochrome --seed 42
"""
import os
import sys

sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, HRFlowable, KeepTogether,
                                Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

# ━━ Fonts (allowed whitelist only) ━━
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f0f0f1')
SECTION_BG    = colors.HexColor('#eeeff0')
CARD_BG       = colors.HexColor('#e9eced')
TABLE_STRIPE  = colors.HexColor('#eaebec')
HEADER_FILL   = colors.HexColor('#475b66')
COVER_BLOCK   = colors.HexColor('#536e7b')
BORDER        = colors.HexColor('#b2c3cc')
ICON          = colors.HexColor('#416f85')
ACCENT        = colors.HexColor('#2b6886')
ACCENT_2      = colors.HexColor('#4a92b7')
TEXT_PRIMARY  = colors.HexColor('#151617')
TEXT_MUTED    = colors.HexColor('#80878a')

OUT = '/home/z/my-project/download/NotiFetch-Brand-LOI.pdf'

# ━━ Page geometry ━━
PAGE_W, PAGE_H = A4
LM = RM = 58
TM, BM = 104, 64
AVAIL_W = PAGE_W - LM - RM          # ~479pt
AVAIL_H = PAGE_H - TM - BM

# ━━ Styles (fill-engine floors: body >=14pt, H1 >=32, H3 >=18) ━━
st_kicker = ParagraphStyle('Kicker', fontName='FreeSerif', fontSize=12, leading=16,
                           textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=4)
st_title = ParagraphStyle('TitleH1', fontName='FreeSerif', fontSize=32, leading=38,
                          textColor=HEADER_FILL, alignment=TA_CENTER, spaceAfter=6)
st_sub = ParagraphStyle('Sub', fontName='FreeSerif', fontSize=14, leading=20,
                        textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=2)
st_ref = ParagraphStyle('Ref', fontName='FreeSerif', fontSize=12, leading=17,
                        textColor=TEXT_PRIMARY)
st_to = ParagraphStyle('ToBlock', fontName='FreeSerif', fontSize=14, leading=21,
                       textColor=TEXT_PRIMARY)
st_body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=14, leading=21,
                         textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=10)
st_clause = ParagraphStyle('ClauseH', fontName='FreeSerif', fontSize=18, leading=24,
                           textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
st_sig = ParagraphStyle('Sig', fontName='FreeSerif', fontSize=14, leading=22,
                        textColor=TEXT_PRIMARY)
st_note = ParagraphStyle('Note', fontName='FreeSerif-Italic', fontSize=10.5, leading=14,
                         textColor=TEXT_MUTED, alignment=TA_CENTER)

story = []

# ━━ Title block ━━
story.append(Paragraph('NOTIFETCH · notifetch.in · BENGALURU', st_kicker))
story.append(Paragraph('<b>LETTER OF INTENT</b>', st_title))
story.append(Paragraph('In-Seat Food Delivery Partnership  ·  Non-Binding', st_sub))
story.append(Spacer(1, 6))
story.append(HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceBefore=2, spaceAfter=2))
story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceBefore=1, spaceAfter=14))

# ━━ Ref + date row ━━
ref_tbl = Table(
    [[Paragraph('Ref: NF/LOI/2026/[XXX]', st_ref),
      Paragraph('Date: [DATE]', ParagraphStyle('RefR', parent=st_ref, alignment=TA_RIGHT))]],
    colWidths=[AVAIL_W * 0.5, AVAIL_W * 0.5], hAlign='CENTER')
ref_tbl.setStyle(TableStyle([
    ('LEFTPADDING', (0, 0), (-1, -1), 0), ('RIGHTPADDING', (0, 0), (-1, -1), 0),
    ('TOPPADDING', (0, 0), (-1, -1), 0), ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
]))
story.append(ref_tbl)
story.append(Spacer(1, 10))

# ━━ Addressee ━━
story.append(Paragraph('To,<br/>The Management,<br/><b>[VENUE NAME]</b>,<br/>[MALL / CINEMA COMPLEX],<br/>[CITY]', st_to))
story.append(Spacer(1, 10))
story.append(Paragraph('<b>Subject: Letter of Intent for In-Seat Food Delivery Partnership (Non-Binding)</b>', st_to))
story.append(Spacer(1, 8))
story.append(Paragraph('Dear Sir / Madam,', st_body))

# ━━ Opening ━━
story.append(Paragraph(
    'This letter records the mutual intent of NotiFetch ("the Platform") and [VENUE NAME] '
    '("the Venue") to explore a seat-to-seat food delivery partnership inside the Venue\'s premises. '
    'NotiFetch operates a QR-based ordering and delivery service that lets a customer scan the seat '
    'in front of them, browse every food-court outlet on a single menu, pay digitally through '
    'Razorpay, and have the order delivered to the seat by a trained runner. We believe this service '
    'will increase per-customer spend at the Venue\'s outlets, shorten counter queues during '
    'show changeovers, and give management a live dashboard view of food-court demand. This letter '
    'is a statement of serious intent to run a structured pilot together; it is not a binding '
    'contract, as set out in Clause 7 below.', st_body))

# ━━ Clauses ━━
CLAUSES = [
    ('1. Purpose',
     'Both parties wish to evaluate, in good faith, whether an in-seat ordering and delivery '
     'service can be operated profitably and smoothly at the Venue. The partnership would allow '
     'customers seated in the auditoriums, food court and lounge areas to place orders from '
     'participating outlets through the NotiFetch platform. The scope, locations and outlets '
     'covered will be finalised jointly before the pilot begins, and either party may suggest '
     'changes at any time during the discussion period.'),
    ('2. Pilot Programme',
     'The parties intend to begin with a pilot of thirty (30) days at the Venue. NotiFetch will '
     'install seat-QR signage and set up the ordering platform at its own cost. During the pilot, '
     'the parties will jointly track weekly orders, average order value, delivery time and '
     'customer feedback. At the end of the pilot, both parties will meet, review the numbers '
     'together, and decide in writing whether to continue under a definitive agreement.'),
    ('3. Commercial Terms',
     'NotiFetch charges the Venue zero (₹0) setup fee and requires no hardware purchase; the '
     'platform runs on ordinary smartphones and the Venue\'s existing kitchen routine. For every '
     'order placed and delivered through the platform, NotiFetch will retain a commission in the '
     'range of six to ten percent (6-10%) of the order value, with the final rate to be fixed in '
     'the definitive agreement based on pilot results. No exclusivity is requested during the '
     'pilot, and the Venue remains free to operate its own counters and promotions.'),
    ('4. Fulfilment and Operations',
     'Participating outlets prepare the food; NotiFetch organises the delivery to the customer\'s '
     'seat with its own trained runner team. NotiFetch provides and maintains the ordering '
     'platform, seat QR codes, a live kitchen console for each outlet, order notifications, and '
     'free staff training. The Venue will provide reasonable access to the food court, auditorium '
     'aisles and lift/escalator routes during show hours so that runners can deliver orders '
     'without disturbing the audience.'),
    ('5. Packaging and Auditorium Safety',
     'All items delivered inside the auditoriums will follow the Venue\'s house rules: dry, '
     'low-odour menu items only, packed in sealed, spill-proof packaging. Hot beverages and '
     'messy items will be delivered only to food-court and lounge seating where the Venue '
     'permits. The Venue\'s written policy on what may be carried into a screen will always '
     'prevail, and the platform can enforce item-level rules screen by screen.'),
    ('6. Payments and Settlement',
     'All customer payments are collected online through Razorpay. NotiFetch will settle each '
     'outlet\'s share weekly, to the bank account the outlet nominates, together with an '
     'itemised statement visible on the Venue\'s dashboard at all times. Each outlet remains '
     'responsible for its own GST and tax compliance on its sales.'),
    ('7. Non-Binding Effect',
     'This letter is a record of intent only and does not create any legally binding obligation '
     'on either party, except for the duty to negotiate in good faith and to keep shared '
     'commercial information confidential. Any pilot under this letter is conditional on the '
     'Venue obtaining its internal authorisations. Either party may withdraw at any time by '
     'written notice without liability. A definitive agreement will be executed before any '
     'commercial scale-up beyond the pilot.'),
    ('8. Validity',
     'This letter of intent is valid for ninety (90) days from the date of signature below. It '
     'may be extended by mutual written consent. If a definitive agreement is signed within this '
     'period, the definitive agreement will replace this letter entirely.'),
]
for head, text in CLAUSES:
    story.append(CondPageBreak(AVAIL_H * 0.18))
    story.extend([KeepTogether([Paragraph(f'<b>{head}</b>', st_clause),
                                Paragraph(text, st_body)])])

# ━━ Closing ━━
story.append(CondPageBreak(AVAIL_H * 0.30))
story.append(Paragraph(
    'We would be glad to walk your team through a live ten-minute demonstration of the platform '
    'at a time of your convenience, and to answer any questions about operations, packaging or '
    'settlements. We look forward to building this together with [VENUE NAME].', st_body))
story.append(Spacer(1, 8))
story.append(Paragraph('Yours sincerely,', st_body))

sig_line = '_' * 30
sig_data = [
    [Paragraph('<b>For NotiFetch</b>', st_sig), Paragraph('<b>For [VENUE NAME]</b>', st_sig)],
    [Paragraph(f'<br/><br/>{sig_line}<br/>Yashas K Gangatkar<br/>Founder, NotiFetch<br/>Date: ____ / ____ / ________', st_sig),
     Paragraph(f'<br/><br/>{sig_line}<br/>Name: ______________________<br/>Designation: ______________<br/>Date: ____ / ____ / ________', st_sig)],
]
sig_tbl = Table(sig_data, colWidths=[AVAIL_W * 0.5, AVAIL_W * 0.5], hAlign='CENTER')
sig_tbl.setStyle(TableStyle([
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ('LEFTPADDING', (0, 0), (-1, -1), 0),
    ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('LINEABOVE', (0, 0), (-1, 0), 0.5, BORDER),
]))
story.append(KeepTogether([Spacer(1, 10), sig_tbl]))
story.append(Spacer(1, 14))
story.append(Paragraph(
    'This Letter of Intent is non-binding and creates no obligation on either party. '
    'Please read it together with Clause 7.', st_note))

# ━━ Header / footer canvas ━━

def _footer(cv, doc):
    cv.saveState()
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.5)
    cv.line(LM, 46, PAGE_W - RM, 46)
    cv.setFont('FreeSerif', 9)
    cv.setFillColor(TEXT_MUTED)
    cv.drawString(LM, 34, 'NotiFetch  ·  notifetch.in  ·  Bengaluru')
    cv.drawRightString(PAGE_W - RM, 34, f'Page {doc.page}')
    cv.restoreState()

def on_first(cv, doc):
    cv.saveState()
    # Letterhead
    cv.setFillColor(TEXT_PRIMARY)
    cv.setFont('FreeSerif-Bold', 24)
    cv.drawString(LM, PAGE_H - 58, 'NOTI', charSpace=2)
    w = pdfmetrics.stringWidth('NOTI', 'FreeSerif-Bold', 24) + 2 * 2
    cv.setFillColor(ACCENT)
    cv.drawString(LM + w, PAGE_H - 58, 'FETCH', charSpace=2)
    cv.setFont('FreeSerif', 10)
    cv.setFillColor(TEXT_MUTED)
    cv.drawRightString(PAGE_W - RM, PAGE_H - 54, 'Seat-to-seat food delivery for cinemas & malls')
    cv.setStrokeColor(ACCENT)
    cv.setLineWidth(2.2)
    cv.line(LM, PAGE_H - 70, PAGE_W - RM, PAGE_H - 70)
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.5)
    cv.line(LM, PAGE_H - 73, PAGE_W - RM, PAGE_H - 73)
    _footer(cv, doc)
    cv.restoreState()

def on_later(cv, doc):
    cv.saveState()
    cv.setFont('FreeSerif', 9)
    cv.setFillColor(TEXT_MUTED)
    cv.drawString(LM, PAGE_H - 46, 'NotiFetch  ·  Letter of Intent (Non-Binding)')
    cv.drawRightString(PAGE_W - RM, PAGE_H - 46, '[VENUE NAME]')
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.7)
    cv.line(LM, PAGE_H - 54, PAGE_W - RM, PAGE_H - 54)
    _footer(cv, doc)
    cv.restoreState()

doc = SimpleDocTemplate(
    OUT, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM,
    title='NotiFetch Brand LOI - In-Seat Food Delivery Partnership (Non-Binding)',
    author='Z.ai', creator='Z.ai',
    subject='Non-binding letter of intent template for cinema and mall partnerships')
doc.build(story, onFirstPage=on_first, onLaterPages=on_later)
print('OK ->', OUT)
