#!/usr/bin/env python3
"""NotiFetch Bengaluru target list + visit playbook - ReportLab (Report route, internal field doc).
No cover (internal ops doc exclusion), no TOC -> SimpleDocTemplate + build().
Palette: design_engine palette-cascade --intent cold --mode minimal --harmony monochrome --seed 42
"""
import sys

sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, HRFlowable, KeepTogether,
                                Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

# ━━ Fonts (allowed whitelist only) ━━
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f0f0f1')
SECTION_BG    = colors.HexColor('#eeeff0')
CARD_BG       = colors.HexColor('#e9eced')
TABLE_STRIPE  = colors.HexColor('#eaebec')
HEADER_FILL   = colors.HexColor('#475b66')
COVER_BLOCK   = colors.HexColor('#536e7b')
BORDER        = colors.HexColor('#b2c3cc')
ICON          = colors.HexColor('#416f85')
ACCENT        = colors.HexColor('#2b6886')
ACCENT_2      = colors.HexColor('#4a92b7')
TEXT_PRIMARY  = colors.HexColor('#151617')
TEXT_MUTED    = colors.HexColor('#80878a')

OUT = '/home/z/my-project/download/NotiFetch-Bengaluru-Targets.pdf'

PAGE_W, PAGE_H = A4
LM = RM = 58
TM, BM = 88, 64
AVAIL_W = PAGE_W - LM - RM
AVAIL_H = PAGE_H - TM - BM

# ━━ Styles ━━
st_kicker = ParagraphStyle('Kicker', fontName='FreeSerif', fontSize=12, leading=16,
                           textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=4)
st_title = ParagraphStyle('TitleH1', fontName='FreeSerif', fontSize=32, leading=38,
                          textColor=HEADER_FILL, alignment=TA_CENTER, spaceAfter=4)
st_body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=14, leading=21,
                         textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=10)
st_h2 = ParagraphStyle('H2', fontName='FreeSerif', fontSize=24, leading=30,
                       textColor=HEADER_FILL, spaceBefore=16, spaceAfter=8)
st_lead = ParagraphStyle('Lead', fontName='FreeSerif', fontSize=14, leading=21,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=6)
st_bullet = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=14, leading=21,
                           textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                           leftIndent=16, firstLineIndent=-11, spaceAfter=4)
st_note = ParagraphStyle('Note', fontName='FreeSerif-Italic', fontSize=12, leading=17,
                         textColor=TEXT_MUTED, spaceBefore=4, spaceAfter=8)
st_th = ParagraphStyle('TH', fontName='FreeSerif', fontSize=12, leading=16,
                       textColor=colors.white, alignment=TA_LEFT)
st_td = ParagraphStyle('TD', fontName='FreeSerif', fontSize=12, leading=17,
                       textColor=TEXT_PRIMARY, alignment=TA_LEFT)
st_email = ParagraphStyle('Email', fontName='FreeSerif', fontSize=12.5, leading=19,
                          textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=6)

story = []

# ━━ Title ━━
story.append(Paragraph('NOTIFETCH · FIELD PACK · SEPTEMBER 2026', st_kicker))
story.append(Paragraph('<b>BENGALURU TARGETS<br/>& VISIT PLAYBOOK</b>', st_title))
story.append(Spacer(1, 4))
story.append(HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceBefore=2, spaceAfter=2))
story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceBefore=1, spaceAfter=14))
story.append(Paragraph(
    'This playbook is everything you carry into the field: the five cinema groups worth walking '
    'into first, the two mall leads you already opened, the exact ten-minute demo that closes the '
    'room, and the words for the four objections you will hear most. The one line to remember all '
    'week is printed on the pitch sheet: Swiggy delivers the cinema\'s own popcorn - NotiFetch '
    'delivers your entire food court. Work the list top to bottom, log every visit the same '
    'evening, and let the ₹2 chai demo do the talking.', st_body))


def make_table(header, rows, ratios, repeat=True):
    data = [[Paragraph(f'<b>{h}</b>', st_th) for h in header]]
    for r in rows:
        data.append([Paragraph(c, st_td) for c in r])
    widths = [ratio * AVAIL_W for ratio in ratios]
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1 if repeat else 0)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      colors.white if i % 2 == 1 else TABLE_STRIPE))
    t.setStyle(TableStyle(style))
    return t

# ━━ Terms strip ━━
story.append(KeepTogether([
    Paragraph('<b>The terms you carry</b>', ParagraphStyle(
        'LeadH', parent=st_lead, fontSize=18, leading=24, textColor=HEADER_FILL,
        spaceBefore=4, spaceAfter=6)),
    make_table(
        ['Term', 'What you say'],
        [
            ['Setup cost', 'Zero rupees to start. We install the seat QR codes and the platform at our own cost.'],
            ['Commission', 'Six to ten percent, only on orders we actually deliver. Swiggy and Zomato take 25-30%.'],
            ['Go-live', 'Seven days from signature to first live order.'],
            ['Hardware', 'None. Runs on any smartphone; kitchens use our console, runners use our app.'],
            ['Pilot', 'Thirty days. You decide at day 30 with real numbers on the table.'],
        ],
        [0.20, 0.80]),
]))
story.append(Spacer(1, 8))

# ━━ Priority targets ━━
story.append(CondPageBreak(AVAIL_H * 0.25))
story.append(Paragraph('<b>Priority targets - walk in this order</b>', st_h2))
story.append(Paragraph(
    'Ranked by how fast a signature can happen and how much one signature is worth. Gopalan first '
    'because it is five venues behind one owner group; Pallavi last because it is the quickest '
    'yes but the smallest prize.', st_lead))
story.append(Paragraph(
    'Skipped from the earlier list: Urvashi Theatre - demolition litigation, a dying venue. '
    'Not worth a visit.', st_note))
story.append(Spacer(1, 2))
targets_tbl = make_table(
    ['Venue and where', 'Why now', 'Ask for', 'Your angle'],
    [
        ['<b>Gopalan Cinemas</b><br/>5 malls, about 15 screens - one owner group (Bannerghatta Rd, Mysore Rd, Old Madras Rd belt)',
         'One signature covers five cinemas. Mid-market food courts, strong family footfall, no aggregator seat-delivery lock-in yet.',
         'Gopalan Group head office - the malls/leasing decision maker, not one theatre manager.',
         '"Sign once and seat-to-seat service goes live in all your cinemas."'],
        ['<b>Miraj Cinemas</b><br/>TGN Lotus Elite',
         'Growing national chain building its Karnataka footprint. A working Bengaluru pilot becomes the rollout story for every new screen.',
         'Miraj Cinemas regional manager (Bengaluru).',
         '"Pilot one screen here. If the numbers work, we talk about every Miraj in the state."'],
        ['<b>MovieTime Cinemas</b><br/>YGR Signature, Rajarajeshwari Nagar + Whitefield',
         'Two Bengaluru venues under a local owner - fast decisions, no corporate committee.',
         'Owner or theatre manager of the YGR group.',
         '"Two halls, one contract, live within a week."'],
        ['<b>Rajhans Cinemas</b><br/>chain expanding fast, roughly 140 screens nationally',
         'They are adding screens right now - every new screen is a fresh install with no legacy habits.',
         'Expansion or operations head at Rajhans Cinemas (India).',
         '"We are the delivery layer you bolt onto every new screen you open."'],
        ['<b>Pallavi Cinemas</b><br/>single screen',
         'One owner, one decision, no committee - fastest possible yes.',
         'Owner-manager directly at the counter, off-peak hours.',
         '"Your hall plus your own counter, delivered to the seat - the multiplex down the road cannot do this today."'],
    ],
    [0.24, 0.27, 0.20, 0.29])
story.append(targets_tbl)

# ━━ Warm leads ━━
story.append(CondPageBreak(AVAIL_H * 0.25))
story.append(Paragraph('<b>Warm leads - Orion and Lulu</b>', st_h2))
story.append(Paragraph(
    'You already walked both malls. Orion went well - the manager was busy but you came out with '
    'three real corporate emails, which makes Orion your only warm door. Lulu went nowhere: '
    'gatekeeper run-around and a claim that Swiggy was already tied up. Treat Lulu as parked, '
    'not dead.', st_lead))
story.append(Spacer(1, 4))
story.append(make_table(
    ['Venue', 'Contact', 'Status', 'Next step'],
    [
        ['<b>Orion Mall</b><br/>(Brigade Group)',
         'jejjujacob@<br/>brigadegroup.com',
         'Leasing - spoke in passing; decision maker not free that day.',
         'Email today using the template below. Ask for 15 minutes with leasing.'],
        ['<b>Orion Mall</b>',
         'priyanka@<br/>orionmalls.com',
         'Marketing - contact collected at the front desk.',
         'CC on the same email thread.'],
        ['<b>Orion Mall</b>',
         'poonamnaik@<br/>orionmalls.com',
         'Marketing - second contact collected.',
         'CC on the same email thread.'],
        ['<b>Lulu Mall Bengaluru</b>',
         'leasingblr@<br/>in.lulumea.com',
         'Gatekeeper loop; told Swiggy was tied up about two weeks ago.',
         'Park for 90 days. Their Swiggy deal is cinema-counter delivery - the food court is still open. Re-approach with pilot numbers from another venue.'],
    ],
    [0.17, 0.24, 0.27, 0.32]))
story.append(Spacer(1, 8))

# ━━ Demo script ━━
story.append(CondPageBreak(AVAIL_H * 0.25))
story.append(Paragraph('<b>The 10-minute demo - two phones, one ₹2 chai</b>', st_h2))
story.append(Paragraph(
    'Phone A is the customer. Phone B is the kitchen, logged in at notifetch.in/staff with the '
    'chef demo account. The Masala Chai sits at ₹2 in the demo store so you can run a real '
    'payment end to end. Do not explain the tech stack - let them watch the ticket move.', st_lead))
story.append(Spacer(1, 4))
story.append(make_table(
    ['Time', 'What you do', 'What you say'],
    [
        ['Before you enter',
         'Phone A charged and on mobile data. Phone B logged into the kitchen console. Demo store open, chai showing ₹2. Five pitch sheets and two printed LOIs in the bag.',
         '-'],
        ['0-1 min',
         'Hand over the pitch sheet and say the one line.',
         '"Swiggy delivers the cinema\'s own popcorn. We deliver your entire food court - to the seat."'],
        ['1-3 min',
         'Phone A: scan the seat QR card. Menu opens - every stall on one menu.',
         '"The customer scans nothing but the seat. No app download, no signup friction."'],
        ['3-5 min',
         'Add the Masala Chai at ₹2 and pay through Razorpay - a real ₹2 transaction.',
         '"Ordered and paid in under two minutes, without leaving the seat."'],
        ['5-7 min',
         'Phone B: the ticket appears in the kitchen console. Tap Accept, then Preparing, then Ready.',
         '"Your kitchen sees the ticket the second it is paid. No phone calls, no paper slips."'],
        ['7-9 min',
         'Phone A: status flips to Ready with the runner assigned. Open the dashboard: order value, your commission line, weekly settlement view.',
         '"And this screen is yours - every order, your cut, settled every week."'],
        ['9-10 min',
         'Close on the LOI, not on applause.',
         '"Thirty-day pilot, zero setup, six to ten percent only on delivered orders. Sign the LOI and you are live in seven days."'],
    ],
    [0.14, 0.42, 0.44]))
story.append(Spacer(1, 8))

# ━━ Objections ━━
story.append(CondPageBreak(AVAIL_H * 0.25))
story.append(Paragraph('<b>Objection cheat sheet</b>', st_h2))
story.append(make_table(
    ['They say', 'You say'],
    [
        ['"PVR already does this."',
         'In-house means their own counter menu and their own app. The food court stalls are not on it. We put every stall on one menu, we supply the trained runners, and the venue earns the commission instead of building an ops team.'],
        ['"Swiggy already does this."',
         'Swiggy\'s cinema service delivers the venue\'s own counter items - that is their national Cinepolis rollout, at aggregator commissions. Ours is multi-stall, venue-branded, six to ten percent, and the customer relationship stays with the venue. Their news actually educates your market for you.'],
        ['"We tried seat delivery and it failed."',
         'The old way was waiters running into dark halls with messy food. We set the rules in software: sealed spill-proof boxes, dry low-odour menus inside the auditoriums, dedicated runners, live tracking. The thirty-day pilot proves it before you commit to anything.'],
        ['"Outside food is banned inside our screens."',
         'Your house rules run the platform. You choose which items may enter a hall - everything dry and sealed - and the full menus stay in the food court and lounge. Policy is set per screen, by you, in the console.'],
    ],
    [0.26, 0.74]))
story.append(Spacer(1, 8))

# ━━ Follow-up email ━━
story.append(CondPageBreak(AVAIL_H * 0.30))
email_inner = [
    Paragraph('<b>Orion follow-up email - send today</b>', ParagraphStyle(
        'EmailH2', parent=st_h2, spaceBefore=0, spaceAfter=10)),
    Paragraph('<b>Subject:</b> Seat-to-seat food delivery for Orion Mall - 15-minute live demo', st_email),
    Paragraph(
        'Hi [Name], we met briefly at Orion Mall on [DATE] when I came in about in-seat food '
        'delivery. One line on what we do: a customer scans the QR on their seat, orders from '
        'every food-court outlet on a single menu, pays online, and our runner team delivers to '
        'the seat while the show runs.', st_email),
    Paragraph(
        'For the mall this is zero setup cost, a six to ten percent commission on delivered '
        'orders only, and a live dashboard of food-court demand. We can go live within seven '
        'days of a signed letter of intent, and we start with a thirty-day pilot so the numbers '
        'decide, not the pitch. I have attached a one-page overview.', st_email),
    Paragraph(
        'Could you give me fifteen minutes with the right person - leasing or marketing - to run '
        'a live ten-minute demo? I can come in any day this week, at any time that suits you.',
        st_email),
    Paragraph(
        'Yashas K Gangatkar<br/>Founder, NotiFetch · notifetch.in · +91 XXXXX XXXXX · Bengaluru',
        st_email),
]
email_card = Table([[email_inner]], colWidths=[AVAIL_W], hAlign='CENTER')
email_card.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
    ('BOX', (0, 0), (-1, -1), 0.8, BORDER),
    ('LINEBEFORE', (0, 0), (0, -1), 2.5, ACCENT),
    ('LEFTPADDING', (0, 0), (-1, -1), 14),
    ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ('TOPPADDING', (0, 0), (-1, -1), 10),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
]))
story.append(email_card)
story.append(Spacer(1, 8))

# ━━ Checklist ━━
story.append(CondPageBreak(AVAIL_H * 0.55))
story.append(Paragraph('<b>Visit checklist</b>', st_h2))
story.append(Paragraph('<b>Before you leave</b>', st_lead))
for b in [
    'Five pitch sheets and two printed LOIs.',
    'Demo seat-QR card and both phones charged above 80 percent.',
    'Phone B logged into the kitchen console; chai showing ₹2 in the demo store.',
]:
    story.append(Paragraph(f'•  {b}', st_bullet))
story.append(Spacer(1, 4))
story.append(Paragraph('<b>At the mall</b>', st_lead))
for b in [
    'Arrive 11:00-12:30 or 16:00-18:30 - never during show changeover.',
    'Ask for the leasing or marketing manager by name at the front desk.',
    'Run the demo at a table or in the food court, not at a crowded counter.',
    'Leave a pitch sheet even if they say no - and always get a name and an email before you walk out.',
]:
    story.append(Paragraph(f'•  {b}', st_bullet))
story.append(Spacer(1, 4))
story.append(Paragraph('<b>Same evening</b>', st_lead))
_same_evening = []
for b in [
    'WhatsApp or email the pitch sheet PDF to every person you met.',
    'Log the visit: name, mood, objection raised, next step.',
    'Set a three-day follow-up reminder.',
    'Verbal yes? Send the LOI PDF the same night and book the signature visit.',
]:
    _same_evening.append(Paragraph(f"•  {b}", st_bullet))
story.append(KeepTogether(_same_evening))

# ━━ Header / footer canvas ━━

def _footer(cv, doc):
    cv.saveState()
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.5)
    cv.line(LM, 46, PAGE_W - RM, 46)
    cv.setFont('FreeSerif', 9)
    cv.setFillColor(TEXT_MUTED)
    cv.drawString(LM, 34, 'NotiFetch  ·  notifetch.in  ·  Bengaluru')
    cv.drawRightString(PAGE_W - RM, 34, f'Page {doc.page}')
    cv.restoreState()

def on_first(cv, doc):
    cv.saveState()
    cv.setFillColor(TEXT_PRIMARY)
    cv.setFont('FreeSerif-Bold', 16)
    cv.drawString(LM, PAGE_H - 46, 'NOTI', charSpace=1.5)
    w = pdfmetrics.stringWidth('NOTI', 'FreeSerif-Bold', 16) + 1.5 * 2
    cv.setFillColor(ACCENT)
    cv.drawString(LM + w, PAGE_H - 46, 'FETCH', charSpace=1.5)
    cv.setFont('FreeSerif', 9)
    cv.setFillColor(TEXT_MUTED)
    cv.drawRightString(PAGE_W - RM, PAGE_H - 44, 'Internal field pack - do not distribute')
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.7)
    cv.line(LM, PAGE_H - 54, PAGE_W - RM, PAGE_H - 54)
    _footer(cv, doc)
    cv.restoreState()

def on_later(cv, doc):
    cv.saveState()
    cv.setFont('FreeSerif', 9)
    cv.setFillColor(TEXT_MUTED)
    cv.drawString(LM, PAGE_H - 46, 'NotiFetch  ·  Bengaluru Targets & Visit Playbook')
    cv.drawRightString(PAGE_W - RM, PAGE_H - 46, 'September 2026')
    cv.setStrokeColor(BORDER)
    cv.setLineWidth(0.7)
    cv.line(LM, PAGE_H - 54, PAGE_W - RM, PAGE_H - 54)
    _footer(cv, doc)
    cv.restoreState()

doc = SimpleDocTemplate(
    OUT, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM,
    title='NotiFetch Bengaluru Targets & Visit Playbook',
    author='Z.ai', creator='Z.ai',
    subject='Field playbook: priority cinema targets, warm mall leads, demo script, objections, checklist')
doc.build(story, onFirstPage=on_first, onLaterPages=on_later)
print('OK ->', OUT)
